version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "mambaforge-latest"
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    pre_install:
      - git update-index --assume-unchanged .rtd-environment.yml docs/conf.py
  apt_packages:
    - libboost-all-dev

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

conda:
  environment: .rtd-environment.yml

formats:
- htmlzip

python:
  install:
  - method: pip
    path: .
    extra_requirements:
    - docs
    - all
